class inicioPAM:
    def __init__(self):
        pass
    def reglas(self):
        return "Reglamento de POO\n 1.Ocultación de la información: Mantener privados los detalles internos de una clase.\n 2.Acceso controlado: Usar métodos públicos para interactuar con los datos.\n 3.Abstracción de la implementación: El código externo no necesita saber el cómo de las operaciones internas.\n 4.Jerarquía de clases: Establecer una relación es un entre clases.\n 5.Reutilización de código: Heredar atributos y métodos de otra clase.\n 6.Especialización: Añadir o modificar comportamientos en las clases derivadas.\n 7.Interfaces comunes: Permitir que objetos diferentes respondan a los mismos mensajes.\n 8.Sobrescritura de métodos: Implementar de forma específica un método heredado.\n 9.Comportamiento dinámico: Decidir en tiempo de ejecución qué método específico ejecutar.\n 10.Modelado conceptual: Enfocarse solo en las características esenciales de un objeto.\n 11.Interfaces claras: Exponer únicamente la funcionalidad relevante.\n 12.Ocultación de la complejidad: Esconder los detalles de implementación complejos."
    def lineas(sefl):
        return "Lineamientos Classroom\n 1.Se requiere 80% de asistencia para tener derecho a evaluación parcial y 80% de trabajos en clase.\n 2.Se permiten 10 minutos de tolerancia y si el alumno llega después de este tiempo puede permanecer en la clase, pero no se tomará la asistencia (Solamente en los horarios de inicio:7:00 a.m y 14:00 p.m).\n3. Las faltas deberán estar justificadas mediante el correo institucional con un plazo máximo de 24 horas posteriores a la hora de falta en clase mediante correo del tutor (a), justificantes entregados fuera de la fecha límite permitido no se aceptan, únicamente se aceptarán recetas médicas y citatorios jurídicos.(De forma física deben ser presentados al tutor para ser validados y de forma posterior emitidos).\n 4. Las tareas y trabajos deberán subirlas al Classroom de forma individual y no se recibirán de manera extemporánea.(Salvo previo justificante validado por el tutor)\n 5. Las tareas y trabajos presentarlos en tiempo y forma. La demora de un trabajo o tarea sin justificante y/o con justificante fuera del límite no se aceptan.\n 6. Utilizar el correo institucional para trabajar bajo la plataforma Google Classroom.\n 7. El plagio o copia de trabajos y/o exámenes, será condicionado a reprobar a la asignatura y se reportará al área correspondiente.\n 8. Cualquier deshonestidad académica será sancionada reprobando el parcial sin derecho a examen final\n 9. En circunstancia de indisciplina o falta de respeto por parte del alumno hacia docentes,administrativos, compañeros o cualquier persona perteneciente a la universidad, se realizará una primera llama de atención, si el alumno hace caso omiso tendrá que abandonar el aula, tres incidencias de este tipo el alumno no tendrá derecho a examen final o parcial.\n 10. Uso de laptops y/o dispositivos móviles quedará limitados a uso exclusivo de las actividades que así lo requieran.\n 11. Prohibido el uso de audífonos durante la clase.\n12. Prohibido comer y/o tomar líquidos en el salón.\n 13. Prohibido sentarse encima de las mesas , así como columpiarse en las sillas.\n 14.Todo tema académido debe ser revisado primeramente por parte del alumno con el docente, de no resolverse, pasar con su respectivo tutor, y de ser necesario con la coordinación de tutores. En caso de no solucionarse pasar a la dirección del programa educativo (debe mantenerse este seguimiento de forma obligatoria)\n 15.Cualquier situación no prevista en el presente reglamento pasar directamente con la dirección del programa educativo.\n 16. El día destinado a entrega de calificaciones todos los estudiantes deben estar presentes, ese día se entregarán exámenes y se brindará retroalimentación\n 17.Este reglamento entra en vigor después de que se firme o se acepte por la mayoría de los estudiantes asistentes a la primera sesión de la materia, una vez firmado o aceptado por el 50% más el jefe de grupo, es vigente para todo alumno inscrito en el curso aunque no esté presente en la primera sesión."
    def fechas(self):
        return "Fechas de Parciales\n 1er Parcial: 30 de Septiembre\n 2do Parcial: 03 de Octubre\n 3do Parcial: 02 de Diciembre\n Examen Final: 08 de Diciembre"
    def porcent(self):
        return "Porcentajes por Parcial\n 1er Parcial:\n Evidencia de Conocimiento 40%\n Evicendia de desemeño 20%\n Evicendia de producto 30%\n Proyecyo Integrador 10%\n 2do Parcial:\n Evidencia de Conocimiento 40%\n Evicendia de desemeño 20%\n Evicendia de producto 20%\n Proyecyo Integrador 20%\n 3er Parcial:\n Evidencia de Conocimiento 20%\n Evicendia de desemeño 10%\n Evicendia de producto 40%\n Proyecyo Integrador 30% "
